x-common-env: &common-spring-env
  SPRING_PROFILES_ACTIVE: dev
  SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
  EUREKA_CLIENT_REGION: default
  EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: myzone
  EUREKA_CLIENT_SERVICEURL_MYZONE: http://service-discovery-container:8761/eureka
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery-container:8761/eureka/

services:
  api-gateway-container:
    image: alejolonber/api-gateway:test
    ports:
      - 8080:8080
    networks:
      - microservices
    environment:
      <<: *common-spring-env
  proxy-client-container:
    image: alejolonber/proxy-client:test
    ports:
      - 8900:8900
    networks:
      - microservices
    environment:
      <<: *common-spring-env
  order-service-container:
    image: alejolonber/order-service:test
    ports:
      - 8300:8300
    networks:
      - microservices
    environment:
      <<: *common-spring-env
  payment-service-container:
    image: alejolonber/payment-service:test
    ports:
      - 8400:8400
    networks:
      - microservices
    environment:
      <<: *common-spring-env
  product-service-container:
    image: alejolonber/product-service:test
    ports:
      - 8500:8500
    networks:
      - microservices
    environment:
      <<: *common-spring-env
  shipping-service-container:
    image: alejolonber/shipping-service:test
    ports:
      - 8600:8600
    networks:
      - microservices
    environment:
      <<: *common-spring-env
  user-service-container:
    image: alejolonber/user-service:test
    ports:
      - 8700:8700
    networks:
      - microservices
    environment:
      <<: *common-spring-env
  favourite-service-container:
    image: alejolonber/favourite-service:test
    ports:
      - 8800:8800
    networks:
      - microservices
    environment:
      <<: *common-spring-env
networks:
  microservices:
    driver: bridge