services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - microservices
  service-discovery-container:
    image: alejolonber/service-discovery:test
    ports:
      - 8761:8761
    networks:
      - microservices
    environment:
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
  cloud-config-container:
    image: alejolonber/cloud-config:test
    ports:
      - 9296:9296
    networks:
      - microservices
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
networks:
  microservices:
    driver: bridge